# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - mikecloud24-functionapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src' # set this to the path to your function app project (now set to src)
  NODE_VERSION: '18' # use Node 18 (LTS) which is supported by Azure Functions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Resolve Project Dependencies Using Npm
        shell: bash
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          npm install
          npm run build --if-present
          npm run test --if-present
          popd

      - name: Zip artifact for deployment (zip contents of package path)
        shell: bash
        run: |
          # create the zip from inside the package path so only app files are included
          pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          zip -r "$GITHUB_WORKSPACE/release.zip" . -x "**/.git/**" "**/node_modules/**/.*" "**/node_modules/**/.cache/**"
          popd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT (OIDC) when using some login flows
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9396D5BE1BF941DD956AFC05283E050D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_38B474FEF03B4883AC4328436F1D2514 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_53663A7201544E6DA8EE706A073D9DC9 }}

      - name: Run Azure Functions Action (deploy zip)
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'mikecloud24-functionapp'
          slot-name: 'Dev'
          package: 'release.zip'

          
