# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js project to Azure Function App - mikecloud24-functionapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src' # function app project path
  NODE_VERSION: '20' # use Node 20 to match package.json engine requirement

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Resolve Project Dependencies, start app for tests, and run tests
        shell: bash
        run: |
          set -euo pipefail
          pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

          # install dependencies and build
          npm install
          npm run build --if-present

          # Start the app in background (redirect logs so job log stays readable)
          echo "Starting app in background..."
          npm run start &> "$GITHUB_WORKSPACE/app.log" &
          APP_PID=$!
          echo "App started with PID $APP_PID; waiting for http://localhost:3000 ..."

          # Wait until the server is ready (npx wait-on will download and run wait-on if needed)
          npx wait-on http://localhost:3000

          # Run tests once the server is responsive
          echo "Server is up — running tests..."
          npm run test --if-present

          # Cleanup background app
          echo "Killing app (PID $APP_PID)..."
          kill "$APP_PID" || true
          popd

      - name: Zip artifact for deployment (zip contents of package path)
        shell: bash
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          zip -r "$GITHUB_WORKSPACE/release.zip" . -x "**/.git/**" "**/node_modules/**/.*" "**/node_modules/**/.cache/**"
          popd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT (OIDC) when using some login flows
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9396D5BE1BF941DD956AFC05283E050D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_38B474FEF03B4883AC4328436F1D2514 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_53663A7201544E6DA8EE706A073D9DC9 }}

      - name: Run Azure Functions Action (deploy zip)
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'mikecloud24-functionapp'
          slot-name: 'Production'
          package: 'release.zip'
          

